### PR TITLE
Main Navigation (no text or data)

### PR DESCRIPTION
**Pull request by aidan-hubley**

### CODE REVIEW

**Comment by 02NRA** [comment]
As mentioned in the meeting today, there are errors with this branch in expo GO; waiting for a response from Alex before approval

**Comment by aidan-hubley** [comment]
@02NRA @dev-arekusandoru They errors appear to be firebase connection issues

**Comment by 02NRA** [comment]
@aidan-hubley this branch has some conflicts; while some are obviously you just adding content, there are some instances around button logic where I am wondering if they are intentional. Please resolve these conflicts, and I'll review again.

**Comment by 02NRA** [comment]
Reviewed changes verbally.

**Review by 02NRA — APPROVED** [review]

**Pull request merged**
