### PR TITLE
Aeh update page for Demo

### PR DESCRIPTION
**Pull request by aidan-hubley**
@dev-arekusandoru can you check if this fits on your screen / your emulator, thanks

### CODE REVIEW

**Comment by dev-arekusandoru** [comment]
Looks good to me

**Comment by aidan-hubley** [comment]
@dev-arekusandoru finally got the status bar . . . . nevermind

**Comment by aidan-hubley** [comment]
@dev-arekusandoru lmk what you think of the color changes, Nason approves. Added some pretty basic stuff to button.js

**Comment by dev-arekusandoru** [comment]
@aidan-hubley I like the idea of adding customization thru props. when I get home today I will look at the colors and let you know my thoughts. so far it looks pretty good. One thing I would suggest is to store those colors under unique names in `tailwind.config.js`. there are already a few there so you can copy the syntax, but this would allow for myself and the others to use the colors you selected without having to memorize the hex codes. another benefit is that you can simply change one hex value in the config file and see the changes everywhere(customizable themes later on)

I do have one thought, however, unrelated to the actual code. I suggest, rather than merging this into master, we merge it into my development branch. Here are a couple benefits i see to this: first, by merging into my branch, i receive your changes directly and can make sure that everything works before it hits master; second, it allows me to receive your changes without having to merge this into master, master into my branch, and then my branch into master.

**Review by dev-arekusandoru — APPROVED** [review]
looks good

**Pull request merged**
